name: Build & Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
    #   - name: Set environment variables
    #     run: |
    #     export FLASK_APP=autoapp.py
      - name: Initialize database & perform migrations
        run: |
          export FLASK_APP=autoapp.py
          export FLASK_DEBUG=1
          flask db stamp head
          flask db migrate
          flask db upgrade
    #   - name: Run application
    #     run: |
    #       export FLASK_APP=autoapp.py
    #       export FLASK_DEBUG=1
    #       flask run --with-threads
      - name: Run tests
        run: |
          export FLASK_APP=autoapp.py
          export FLASK_DEBUG=1
          flask test
