name: Build and Run

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: migrate db
        run: |
          export FLASK_APP=autoapp.py
          export FLASK_DEBUG=1
          flask db stamp head
          flask db migrate
          flask db upgrade
      - name: run tests
        run: |
          export FLASK_APP=autoapp.py
          export FLASK_DEBUG=1
          flask test
